--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:wNQjtMFPdIGp8sdrbKNCRg==$fF1GUhAFT8GEY6fheVMpOoM1Eaw6Lej/aGVvbPw+mLo=:cXW55NhJ4hIs7TFzijoWz3OL+61bZ3/H5P3kTnWH7rw=';

--
-- User Configurations
--






--
-- Tablespaces
--

CREATE TABLESPACE alumnos OWNER postgres LOCATION E'D:\\Databases\\PostgreSQL\\pg_tblspc';


--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- Database "alumnos" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: alumnos; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE alumnos WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Mexico.1252' TABLESPACE = alumnos;


ALTER DATABASE alumnos OWNER TO postgres;

\connect alumnos

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: alumnos_schema; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA alumnos_schema;


ALTER SCHEMA alumnos_schema OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alumno; Type: TABLE; Schema: alumnos_schema; Owner: postgres
--

CREATE TABLE alumnos_schema.alumno (
    nombres character varying,
    edad integer,
    apellido_materno character varying,
    apellido_paterno character varying,
    id integer NOT NULL
);


ALTER TABLE alumnos_schema.alumno OWNER TO postgres;

--
-- Name: alumnos_id_seq; Type: SEQUENCE; Schema: alumnos_schema; Owner: postgres
--

ALTER TABLE alumnos_schema.alumno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alumnos_schema.alumnos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999
    CACHE 1
);


--
-- Name: tarea; Type: TABLE; Schema: alumnos_schema; Owner: postgres
--

CREATE TABLE alumnos_schema.tarea (
    nombre character varying,
    id integer NOT NULL,
    alumno_id integer NOT NULL
);


ALTER TABLE alumnos_schema.tarea OWNER TO postgres;

--
-- Name: tarea_id_seq; Type: SEQUENCE; Schema: alumnos_schema; Owner: postgres
--

ALTER TABLE alumnos_schema.tarea ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alumnos_schema.tarea_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999
    CACHE 1
);


--
-- Data for Name: alumno; Type: TABLE DATA; Schema: alumnos_schema; Owner: postgres
--

COPY alumnos_schema.alumno (nombres, edad, apellido_materno, apellido_paterno, id) FROM stdin;
Moises	27	\N	\N	3
Moises	27	Diaz	Diaz	4
Arturiano Benito	45	Davila	Perez	1
Arturiano Salvador	27	Perez	Andovila	5
\.


--
-- Data for Name: tarea; Type: TABLE DATA; Schema: alumnos_schema; Owner: postgres
--

COPY alumnos_schema.tarea (nombre, id, alumno_id) FROM stdin;
\.


--
-- Name: alumnos_id_seq; Type: SEQUENCE SET; Schema: alumnos_schema; Owner: postgres
--

SELECT pg_catalog.setval('alumnos_schema.alumnos_id_seq', 5, true);


--
-- Name: tarea_id_seq; Type: SEQUENCE SET; Schema: alumnos_schema; Owner: postgres
--

SELECT pg_catalog.setval('alumnos_schema.tarea_id_seq', 1, true);


--
-- Name: alumno alumno_pk; Type: CONSTRAINT; Schema: alumnos_schema; Owner: postgres
--

ALTER TABLE ONLY alumnos_schema.alumno
    ADD CONSTRAINT alumno_pk PRIMARY KEY (id);


--
-- Name: tarea tareas_alumnos_id_fk; Type: FK CONSTRAINT; Schema: alumnos_schema; Owner: postgres
--

ALTER TABLE ONLY alumnos_schema.tarea
    ADD CONSTRAINT tareas_alumnos_id_fk FOREIGN KEY (alumno_id) REFERENCES alumnos_schema.alumno(id);


--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete
--

